# @title Get all todos
GET {{API_URL}}/todo

HTTP/1.1 200  - OK
x-powered-by: Express
vary: Origin
content-type: application/json; charset=utf-8
content-length: 133
etag: W/"85-1JRz/Xb9O/WukI5FnLHM7AZIOlw"
date: Mon, 07 Oct 2024 09:03:52 GMT
connection: close
###
# @title Delete all todos
DELETE {{API_URL}}/todo

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 31
etag: W/"1f-yTVzSstqb1Hzz7E3IawHap8mhtg"
date: Sat, 05 Oct 2024 15:47:28 GMT
connection: keep-alive
keep-alive: timeout=5
###
# @title Create a todo
POST {{API_URL}}/todo
Content-Type: application/json

{
  "priority": "A",
  "description": "Buy milk"
}

HTTP/1.1 201  - Created
x-powered-by: Express
vary: Origin
content-type: application/json; charset=utf-8
content-length: 142
etag: W/"8e-jY6tdnZIVW+Xvps8VlmQdKsbQDk"
date: Mon, 07 Oct 2024 09:04:14 GMT
connection: close
###
# @title Create a todo with null priority
POST {{API_URL}}/todo
Content-Type: application/json

{
  "priority": null,
  "description": "Hello World!"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 131
etag: W/"83-lW+D2mq4hWKjXMAlp5UEYPUDvaM"
date: Sat, 05 Oct 2024 15:47:33 GMT
connection: keep-alive
keep-alive: timeout=5
###
# @title Create a todo without priority
POST {{API_URL}}/todo
Content-Type: application/json

{
  "description": "Hello World!"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 131
etag: W/"83-wc09/xsksNZT5XwGlxs6uTt004Y"
date: Sat, 05 Oct 2024 15:47:43 GMT
connection: keep-alive
keep-alive: timeout=5
###
# @title Create a faulty todo with wrong priority
POST {{API_URL}}/todo
Content-Type: application/json

{
  "priority": "1",
  "description": "Hello World!"
}

HTTP/1.1 400  - Bad Request
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 92
etag: W/"5c-1HWXtL5PoWXdiFDDSbL4KrvBUvI"
date: Sat, 05 Oct 2024 15:47:46 GMT
connection: keep-alive
keep-alive: timeout=5
###
# @title Create a faulty todo with wrong description
POST {{API_URL}}/todo
Content-Type: application/json

{
  "description": null
}

HTTP/1.1 400  - Bad Request
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 204
etag: W/"cc-DnT8/FA2lM+kWdzoPUWo996OnxA"
date: Sat, 05 Oct 2024 15:47:48 GMT
connection: keep-alive
keep-alive: timeout=5
###
# @title Create a faulty todo without description
POST {{API_URL}}/todo
Content-Type: application/json

{
}

HTTP/1.1 400  - Bad Request
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 204
etag: W/"cc-DnT8/FA2lM+kWdzoPUWo996OnxA"
date: Sat, 05 Oct 2024 15:47:56 GMT
connection: keep-alive
keep-alive: timeout=5